//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProofOfConcept.Web.AccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/ProofOfConcept.WcfService.DataContract")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((this.AccountNumberField.Equals(value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetBalance", ReplyAction="http://tempuri.org/IAccountService/GetBalanceResponse")]
        ProofOfConcept.Web.AccountService.ServiceResponse GetBalance(long accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAccountService/GetBalance", ReplyAction="http://tempuri.org/IAccountService/GetBalanceResponse")]
        System.IAsyncResult BeginGetBalance(long accountNumber, System.AsyncCallback callback, object asyncState);
        
        ProofOfConcept.Web.AccountService.ServiceResponse EndGetBalance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/InvokeDeposit", ReplyAction="http://tempuri.org/IAccountService/InvokeDepositResponse")]
        ProofOfConcept.Web.AccountService.ServiceResponse InvokeDeposit(long accountNumber, decimal Amount, string Currency);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAccountService/InvokeDeposit", ReplyAction="http://tempuri.org/IAccountService/InvokeDepositResponse")]
        System.IAsyncResult BeginInvokeDeposit(long accountNumber, decimal Amount, string Currency, System.AsyncCallback callback, object asyncState);
        
        ProofOfConcept.Web.AccountService.ServiceResponse EndInvokeDeposit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/InvokeWithdraw", ReplyAction="http://tempuri.org/IAccountService/InvokeWithdrawResponse")]
        ProofOfConcept.Web.AccountService.ServiceResponse InvokeWithdraw(long accountNumber, decimal Amount, string Currency);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAccountService/InvokeWithdraw", ReplyAction="http://tempuri.org/IAccountService/InvokeWithdrawResponse")]
        System.IAsyncResult BeginInvokeWithdraw(long accountNumber, decimal Amount, string Currency, System.AsyncCallback callback, object asyncState);
        
        ProofOfConcept.Web.AccountService.ServiceResponse EndInvokeWithdraw(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : ProofOfConcept.Web.AccountService.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProofOfConcept.Web.AccountService.ServiceResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProofOfConcept.Web.AccountService.ServiceResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokeDepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InvokeDepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProofOfConcept.Web.AccountService.ServiceResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProofOfConcept.Web.AccountService.ServiceResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokeWithdrawCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InvokeWithdrawCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProofOfConcept.Web.AccountService.ServiceResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProofOfConcept.Web.AccountService.ServiceResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<ProofOfConcept.Web.AccountService.IAccountService>, ProofOfConcept.Web.AccountService.IAccountService {
        
        private BeginOperationDelegate onBeginGetBalanceDelegate;
        
        private EndOperationDelegate onEndGetBalanceDelegate;
        
        private System.Threading.SendOrPostCallback onGetBalanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginInvokeDepositDelegate;
        
        private EndOperationDelegate onEndInvokeDepositDelegate;
        
        private System.Threading.SendOrPostCallback onInvokeDepositCompletedDelegate;
        
        private BeginOperationDelegate onBeginInvokeWithdrawDelegate;
        
        private EndOperationDelegate onEndInvokeWithdrawDelegate;
        
        private System.Threading.SendOrPostCallback onInvokeWithdrawCompletedDelegate;
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetBalanceCompletedEventArgs> GetBalanceCompleted;
        
        public event System.EventHandler<InvokeDepositCompletedEventArgs> InvokeDepositCompleted;
        
        public event System.EventHandler<InvokeWithdrawCompletedEventArgs> InvokeWithdrawCompleted;
        
        public ProofOfConcept.Web.AccountService.ServiceResponse GetBalance(long accountNumber) {
            return base.Channel.GetBalance(accountNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetBalance(long accountNumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBalance(accountNumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProofOfConcept.Web.AccountService.ServiceResponse EndGetBalance(System.IAsyncResult result) {
            return base.Channel.EndGetBalance(result);
        }
        
        private System.IAsyncResult OnBeginGetBalance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long accountNumber = ((long)(inValues[0]));
            return this.BeginGetBalance(accountNumber, callback, asyncState);
        }
        
        private object[] OnEndGetBalance(System.IAsyncResult result) {
            ProofOfConcept.Web.AccountService.ServiceResponse retVal = this.EndGetBalance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBalanceCompleted(object state) {
            if ((this.GetBalanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBalanceAsync(long accountNumber) {
            this.GetBalanceAsync(accountNumber, null);
        }
        
        public void GetBalanceAsync(long accountNumber, object userState) {
            if ((this.onBeginGetBalanceDelegate == null)) {
                this.onBeginGetBalanceDelegate = new BeginOperationDelegate(this.OnBeginGetBalance);
            }
            if ((this.onEndGetBalanceDelegate == null)) {
                this.onEndGetBalanceDelegate = new EndOperationDelegate(this.OnEndGetBalance);
            }
            if ((this.onGetBalanceCompletedDelegate == null)) {
                this.onGetBalanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBalanceCompleted);
            }
            base.InvokeAsync(this.onBeginGetBalanceDelegate, new object[] {
                        accountNumber}, this.onEndGetBalanceDelegate, this.onGetBalanceCompletedDelegate, userState);
        }
        
        public ProofOfConcept.Web.AccountService.ServiceResponse InvokeDeposit(long accountNumber, decimal Amount, string Currency) {
            return base.Channel.InvokeDeposit(accountNumber, Amount, Currency);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInvokeDeposit(long accountNumber, decimal Amount, string Currency, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInvokeDeposit(accountNumber, Amount, Currency, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProofOfConcept.Web.AccountService.ServiceResponse EndInvokeDeposit(System.IAsyncResult result) {
            return base.Channel.EndInvokeDeposit(result);
        }
        
        private System.IAsyncResult OnBeginInvokeDeposit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long accountNumber = ((long)(inValues[0]));
            decimal Amount = ((decimal)(inValues[1]));
            string Currency = ((string)(inValues[2]));
            return this.BeginInvokeDeposit(accountNumber, Amount, Currency, callback, asyncState);
        }
        
        private object[] OnEndInvokeDeposit(System.IAsyncResult result) {
            ProofOfConcept.Web.AccountService.ServiceResponse retVal = this.EndInvokeDeposit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInvokeDepositCompleted(object state) {
            if ((this.InvokeDepositCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InvokeDepositCompleted(this, new InvokeDepositCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InvokeDepositAsync(long accountNumber, decimal Amount, string Currency) {
            this.InvokeDepositAsync(accountNumber, Amount, Currency, null);
        }
        
        public void InvokeDepositAsync(long accountNumber, decimal Amount, string Currency, object userState) {
            if ((this.onBeginInvokeDepositDelegate == null)) {
                this.onBeginInvokeDepositDelegate = new BeginOperationDelegate(this.OnBeginInvokeDeposit);
            }
            if ((this.onEndInvokeDepositDelegate == null)) {
                this.onEndInvokeDepositDelegate = new EndOperationDelegate(this.OnEndInvokeDeposit);
            }
            if ((this.onInvokeDepositCompletedDelegate == null)) {
                this.onInvokeDepositCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInvokeDepositCompleted);
            }
            base.InvokeAsync(this.onBeginInvokeDepositDelegate, new object[] {
                        accountNumber,
                        Amount,
                        Currency}, this.onEndInvokeDepositDelegate, this.onInvokeDepositCompletedDelegate, userState);
        }
        
        public ProofOfConcept.Web.AccountService.ServiceResponse InvokeWithdraw(long accountNumber, decimal Amount, string Currency) {
            return base.Channel.InvokeWithdraw(accountNumber, Amount, Currency);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInvokeWithdraw(long accountNumber, decimal Amount, string Currency, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInvokeWithdraw(accountNumber, Amount, Currency, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProofOfConcept.Web.AccountService.ServiceResponse EndInvokeWithdraw(System.IAsyncResult result) {
            return base.Channel.EndInvokeWithdraw(result);
        }
        
        private System.IAsyncResult OnBeginInvokeWithdraw(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long accountNumber = ((long)(inValues[0]));
            decimal Amount = ((decimal)(inValues[1]));
            string Currency = ((string)(inValues[2]));
            return this.BeginInvokeWithdraw(accountNumber, Amount, Currency, callback, asyncState);
        }
        
        private object[] OnEndInvokeWithdraw(System.IAsyncResult result) {
            ProofOfConcept.Web.AccountService.ServiceResponse retVal = this.EndInvokeWithdraw(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInvokeWithdrawCompleted(object state) {
            if ((this.InvokeWithdrawCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InvokeWithdrawCompleted(this, new InvokeWithdrawCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InvokeWithdrawAsync(long accountNumber, decimal Amount, string Currency) {
            this.InvokeWithdrawAsync(accountNumber, Amount, Currency, null);
        }
        
        public void InvokeWithdrawAsync(long accountNumber, decimal Amount, string Currency, object userState) {
            if ((this.onBeginInvokeWithdrawDelegate == null)) {
                this.onBeginInvokeWithdrawDelegate = new BeginOperationDelegate(this.OnBeginInvokeWithdraw);
            }
            if ((this.onEndInvokeWithdrawDelegate == null)) {
                this.onEndInvokeWithdrawDelegate = new EndOperationDelegate(this.OnEndInvokeWithdraw);
            }
            if ((this.onInvokeWithdrawCompletedDelegate == null)) {
                this.onInvokeWithdrawCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInvokeWithdrawCompleted);
            }
            base.InvokeAsync(this.onBeginInvokeWithdrawDelegate, new object[] {
                        accountNumber,
                        Amount,
                        Currency}, this.onEndInvokeWithdrawDelegate, this.onInvokeWithdrawCompletedDelegate, userState);
        }
    }
}
